import mongoose from "mongoose";
import { ID_SUFFIX, REF_STARBUCKS, TYPE_MENU } from "../constants";

const generateId = (index: number) => new mongoose.Types.ObjectId(`${REF_STARBUCKS}${TYPE_MENU}${ID_SUFFIX}${(1000 + index).toString().padStart(6, "0")}`);

export const menus = [
	{
		_id: generateId(1),
		name: "Classic Jollof Rice",
		price: 3500,
		description: "Spicy and smoky party jollof rice served with fried plantains and your choice of protein.",
		image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Jollof_rice_with_chicken_and_fried_plantains.jpg/800px-Jollof_rice_with_chicken_and_fried_plantains.jpg",
		category: "Rice Dishes",
		veg: "non-veg",
		restaurantID: "smarteats",
		hidden: false,
		taxPercent: 7.5,
	},
	{
		_id: generateId(2),
		name: "Pounded Yam and Egusi Soup",
		price: 4500,
		description: "Smooth, freshly pounded yam served with rich egusi soup made with assorted meats and fish.",
		image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Pounded_yam_and_egusi_soup.jpg/800px-Pounded_yam_and_egusi_soup.jpg",
		category: "Soups & Swallows",
		veg: "non-veg",
		restaurantID: "smarteats",
		hidden: false,
		taxPercent: 7.5,
	},
	{
		_id: generateId(3),
		name: "Beef Suya",
		price: 2500,
		description: "Spicy grilled beef skewers garnished with fresh onions, tomatoes, and extra yaji spice.",
		image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Suya_-_Nigerian_street_food.jpg/800px-Suya_-_Nigerian_street_food.jpg",
		category: "Grilled",
		veg: "non-veg",
		restaurantID: "smarteats",
		hidden: false,
		taxPercent: 7.5,
	},
	{
		_id: generateId(4),
		name: "Fried Rice with Chicken",
		price: 3800,
		description: "Nigerian style fried rice with vegetables and liver, served with fried chicken.",
		image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Fried_Rice_with_Fried_Chicken.jpg/800px-Fried_Rice_with_Fried_Chicken.jpg",
		category: "Rice Dishes",
		veg: "non-veg",
		restaurantID: "smarteats",
		hidden: false,
		taxPercent: 7.5,
	},
	{
		_id: generateId(5),
		name: "Pepper Soup (Catfish)",
		price: 4000,
		description: "Hot and spicy point-and-kill catfish pepper soup.",
		image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Catfish_Pepper_Soup.jpg/800px-Catfish_Pepper_Soup.jpg",
		category: "Soups & Swallows",
		veg: "non-veg",
		restaurantID: "smarteats",
		hidden: false,
		taxPercent: 7.5,
	},
	{
		_id: generateId(6),
		name: "Moi Moi",
		price: 1500,
		description: "Steamed bean pudding made with washed and peeled black-eyed peas, onions, and fresh ground red peppers.",
		image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Moi_Moi_in_leaves.jpg/800px-Moi_Moi_in_leaves.jpg",
		category: "Snacks",
		veg: "contains-egg",
		restaurantID: "smarteats",
		hidden: false,
		taxPercent: 7.5,
	},
	{
		_id: generateId(7),
		name: "Zobo Drink",
		price: 800,
		description: "Chilled hibiscus tea with ginger and pineapple flavor.",
		image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Zobo_Drink_in_a_glass.jpg/800px-Zobo_Drink_in_a_glass.jpg",
		category: "Drinks",
		veg: "veg",
		restaurantID: "smarteats",
		hidden: false,
		taxPercent: 7.5,
	}
];
